spring:
  application:
    name: insurance-user
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    url: jdbc:mysql://47.100.79.203:3306/insurance
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 18884
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dm.insurance.entity