spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
    gateway:
      routes:
        - id: insurance_user_route
          uri: lb://insurance-user
          predicates:
              - Path=/api/user/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_policy_person
          uri: lb://insurance-policy-person
          predicates:
              - Path=/api/policy/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_third_party
          uri: lb://insurance-third-party
          predicates:
              - Path=/api/third/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_city
          uri: lb://insurance-city
          predicates:
              - Path=/api/insuranceCity/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_car_insur
          uri: lb://insurance-car-insur
          predicates:
              - Path=/api/carInsur/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_car_info
          uri: lb://insurance-car-info
          predicates:
              - Path=/api/insuranceCarInfo/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_other_insur_info2
          uri: lb://insurance-other-insur-info2
          predicates:
              - Path=/api/otherInsur/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}