server:
  port: 12000

spring:
  application:
    name: insurance-car-insur
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
  datasource:
    url: jdbc:mysql://47.100.79.206:3306/insurance
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.dm.insurance: debug