server:
  port: 18888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
  application:
    name: insurance-order
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
