spring:
  application:
    name: insurance-policy-person
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: rootroot
    username: root
    url: jdbc:mysql://47.100.79.206:3306/insurance?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.100.79.206
    port: 6379
    timeout: 5000
server:
  port: 12121
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dm.insurance.entity