spring:
  application:
<<<<<<< HEAD
    name: insurance-user
=======
    name: insurance-user-wb
>>>>>>> e5f74f7119095082e7dff25675b6ee4f26ce98e1
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
server:
  port: 18884