spring:
  application:
    name: insurance-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启自动路由功能
      routes:
        - id: insurance_user_route
          uri: lb://insurance-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_policy_person
          uri: lb://insurance-policy-person
          predicates:
            - Path=/api/policy/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_third_party
          uri: lb://insurance-third-party
          predicates:
            - Path=/api/third/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_city
          uri: lb://insurance-city
          predicates:
            - Path=/api/insuranceCity/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_car_insur
          uri: lb://insurance-car-insur
          predicates:
            - Path=/api/carInsur/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_car_info
          uri: lb://insurance-car-info
          predicates:
            - Path=/api/insuranceCarInfo/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance_other_insur_info2
          uri: lb://insurance-other-insur-info2
          predicates:
            - Path=/api/otherInsur/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: insurance-pay
          uri: lb://insurance-pay
          predicates:
            - Path=/api/insurance/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: claim-form
          uri: lb://claims-form
          predicates:
            - Path=/Api/claim/form/**
          filters:
            - RewritePath=/Api/(?<segment>.*),/$\{segment}

        - id: claim-indemnity
          uri: lb://claims-indemnity
          predicates:
            - Path=/Api/claim/indemnity/**
          filters:
            - RewritePath=/Api/(?<segment>.*),/$\{segment}

        - id: claim-loss-lossassessment
          uri: lb://claims-loss-assessment
          predicates:
            - Path=/Api/claim/lossassessment/**
          filters:
            - RewritePath=/Api/(?<segment>.*),/$\{segment}

        - id: claim-material
          uri: lb://claims-material
          predicates:
            - Path=/Api/claim/material/**
          filters:
            - RewritePath=/Api/(?<segment>.*),/$\{segment}

        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/Api/**
          filters:
            - RewritePath=/Api/(?<segment>.*),/$\{segment}
server:
  port: 80