spring:
  application:
    name: insurance-city
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
  datasource:
    url: jdbc:mysql://47.100.79.206:3306/insurance?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.100.79.206
    port: 6379
    timeout: 5000
server:
  port: 16666
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.dm.insurance.dao: debug